### ISSUE TITLE
tox doesn't allow build for multiple SDKs

### ISSUE THREAD

**Issue by fifieldt** [fifieldt/openstack-firstapp#3]
Previous makefile allowed specification of an SDK to build eg libcloud, jclouds etc

tox script as it is only runs sphinx build without any options which means no code gets includede

**Comment by sc68cal** [comment]
Looks like you beat me to it, with bb5bc1bb05f93461fac5618f88d9bd1ad08e6d15

**Comment by fifieldt** [comment]
yup - fixed
